export enum LearningActivityType {
    MULTIPLE_OPTION_THEORY = 'MULTIPLE_OPTION_THEORY',         // FR 19
    MULTIPLE_OPTION_INCOMPLETE_SENTENCE = 'MULTIPLE_OPTION_INCOMPLETE_SENTENCE', // FR 20
    MULTIPLE_OPTION_VOCABULARY = 'MULTIPLE_OPTION_VOCABULARY', // FR 21
    MULTIPLE_OPTION_IMAGE = 'MULTIPLE_OPTION_IMAGE',           // FR 22
    WRITTEN_RESPONSE = 'WRITTEN_RESPONSE',                     // FR 23
    EMAIL_NOTIFICATION = 'EMAIL_NOTIFICATION',                 // FR 24
    SHOW_RESULTS = 'SHOW_RESULTS',                             // FR 25
}